server:
  port: 8080
  mode: debug  # debug or release

database:
  driver: mysql
  host: 60.205.106.216
  port: 3306
  username: root
  password: Qq139547
  dbname: user_center
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

jwt:
  secret_key: your_secret_key
  expire_hours: 24

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

log:
  level: debug
  filename: ./logs/app.log
  max_size: 100    # megabytes
  max_age: 7       # days
  max_backups: 10
  format: text     # 可选值: "json" 或 "text"